services:
  redis:
    image: redis:7
    container_name: cocanvas-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    container_name: cocanvas-mysql
    environment:
      MYSQL_ROOT_PASSWORD: cocanvas123
      MYSQL_DATABASE: cocanvas
    ports:
      - "3306:3306"
    volumes:
      - cocanvas-mysql-data:/var/lib/mysql

volumes:
  cocanvas-mysql-data:
